name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t healthcare-devops . 

  
  - name: Login to docker hub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

  - name: Changing the image tag
      run: docker tag healthcare-devops ${{secrets.DOCKER_USERNAME}}/healthcare-devops

  - name: Push docker image into dockerhub
      run: docker push ${{secrets.DOCKER_USERNAME}}/healthcare-devops
